apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: b2c-demo-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omermaman1411-ctrl/devopsai-b2c-monorepo.git
    targetRevision: master
    path: gitops/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev   # או devopsai-dev אם ככה קראתם ל-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
